<a href="https://colab.research.google.com/github/rubaiyat-sholi/Numpy_Basics-4.0/blob/main/Numpy_Basics_4_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problems

In [5]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
    Z = rolling(np.arange(10), 3)
    print(Z)
      
    Z = np.arange(10)
    print(sliding_window_view(Z, window_shape=3))



In [7]:
# 77. How to negate a boolean, or to change the sign of a float inplace?
import numpy as np
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.78208624, -0.31851182, -0.4370322 , -0.18188675, -0.57930273,
        0.96232454,  0.66735176, -0.29540322, -0.9808393 ,  0.28871227,
       -0.68755065, -0.60028547,  0.44907881, -0.75114324, -0.74353258,
       -0.30429313,  0.3462888 ,  0.43697286,  0.01410286,  0.28017567,
        0.13140411,  0.71227079, -0.06781064,  0.35150865,  0.92806246,
        0.02102889, -0.29138052,  0.16537755,  0.68986886, -0.75981031,
        0.18953258,  0.30752764,  0.51287622, -0.97133556, -0.77094714,
        0.09996734,  0.07219088,  0.4700801 , -0.45719299, -0.55248301,
        0.4715239 , -0.02361287, -0.72758108, -0.93557245, -0.83215603,
       -0.61573102,  0.01892526,  0.60082043,  0.12808891,  0.39679352,
        0.5057511 ,  0.41782216,  0.34638275, -0.99212161, -0.59971879,
        0.69028339,  0.78612174,  0.98090134,  0.94753296,  0.75574298,
       -0.975586  , -0.1065325 , -0.1922148 , -0.2759824 ,  0.40802022,
       -0.11715005,  0.10812618, -0.72056036, -0.45971835, -0.62

In [8]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.49631188  8.53394553  9.42130809  4.90105912  4.99973368  1.250569
 13.1772991  10.24544894 16.31530408  2.07696257]


In [9]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.0275703   1.14116377  0.72628803  2.20839177  4.0505771  10.20681841
   7.36667827 15.92218287 10.31189689 11.61501343]
 [18.21543404  1.04429215  0.53985981  2.22536508  4.23297103 10.41140514
   7.55548693 16.09636088 10.44676162 11.79599395]
 [11.26225227  4.56663332  0.38548192  6.09487706  5.48134025  4.66758135
   0.65245052  8.54801522 14.50882266  4.51628062]
 [ 1.125975    8.05140901  2.26047113 14.2972168   3.21761278  4.63906699
   9.45417884  1.89346286 15.80851314  5.79925809]
 [12.56864685  3.97384002  0.60425242  4.91756962  5.64813463  5.83848905
   1.95369428  9.91095573 14.19987864  5.8548599 ]
 [ 4.03687927  9.52238776  0.60264177 14.00910659  6.01764828  1.47501299
   6.52891117  0.80898104 17.86865208  2.99310989]
 [16.75305853  0.98262807  1.29693006  1.4109397   3.5227132   8.98102906
   6.09330617 14.6427951  10.20002323 10.33563705]
 [ 6.6012675   7.53777434  0.33347604 11.01141444  5.63094814  0.66020154
   3.98223261  3.58271874 16.45395743  0.3136506 ]


In [10]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 0 4 8 4 1 4 3 3 3]
 [0 0 4 7 3 3 4 7 3 1]
 [6 5 1 0 6 8 4 6 8 3]
 [0 3 5 7 9 8 1 6 2 5]
 [1 6 5 5 6 2 8 3 5 6]
 [6 8 6 7 1 7 3 5 2 2]
 [5 3 8 5 9 6 6 1 3 1]
 [5 8 9 6 3 3 1 8 3 2]
 [0 3 0 9 1 7 6 6 1 5]
 [1 3 8 9 8 3 2 0 5 6]]
[[0 0 0 0 0]
 [0 5 0 4 8]
 [0 0 0 4 7]
 [0 6 5 1 0]
 [0 0 3 5 7]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [15]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [16]:
# 82. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


In [17]:
# 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [20]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 0 4]
   [2 0 4]
   [1 3 3]]

  [[0 4 2]
   [0 4 0]
   [3 3 0]]

  [[4 2 2]
   [4 0 1]
   [3 0 2]]

  [[2 2 3]
   [0 1 0]
   [0 2 0]]

  [[2 3 2]
   [1 0 2]
   [2 0 2]]

  [[3 2 4]
   [0 2 2]
   [0 2 4]]

  [[2 4 3]
   [2 2 1]
   [2 4 0]]

  [[4 3 3]
   [2 1 1]
   [4 0 3]]]


 [[[2 0 4]
   [1 3 3]
   [0 3 4]]

  [[0 4 0]
   [3 3 0]
   [3 4 3]]

  [[4 0 1]
   [3 0 2]
   [4 3 1]]

  [[0 1 0]
   [0 2 0]
   [3 1 0]]

  [[1 0 2]
   [2 0 2]
   [1 0 4]]

  [[0 2 2]
   [0 2 4]
   [0 4 1]]

  [[2 2 1]
   [2 4 0]
   [4 1 1]]

  [[2 1 1]
   [4 0 3]
   [1 1 1]]]


 [[[1 3 3]
   [0 3 4]
   [1 2 2]]

  [[3 3 0]
   [3 4 3]
   [2 2 4]]

  [[3 0 2]
   [4 3 1]
   [2 4 4]]

  [[0 2 0]
   [3 1 0]
   [4 4 0]]

  [[2 0 2]
   [1 0 4]
   [4 0 1]]

  [[0 2 4]
   [0 4 1]
   [0 1 4]]

  [[2 4 0]
   [4 1 1]
   [1 4 4]]

  [[4 0 3]
   [1 1 1]
   [4 4 0]]]


 [[[0 3 4]
   [1 2 2]
   [4 1 2]]

  [[3 4 3]
   [2 2 4]
   [1 2 0]]

  [[4 3 1]
   [2 4 4]
   [2 0 2]]

  [[3 1 0]
   [4 4 0]
   [0 2 0]]

  [[1 0 4]
   

In [21]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 14 12 13  5]
 [14  7 10 16 11]
 [12 10  9 42  4]
 [13 16 42  3  9]
 [ 5 11  4  9  7]]


In [22]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [23]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [24]:
# 88. How to implement the Game of Life using numpy arrays?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
# 89. How to get the n largest values of an array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


In [26]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [27]:
# 91. How to create a record array from a regular array? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [29]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.76 s per loop
10 loops, best of 5: 146 ms per loop
10 loops, best of 5: 126 ms per loop


In [31]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 6]


In [32]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 4 2]
 [4 3 3]
 [0 1 4]
 [4 4 0]
 [3 0 2]
 [2 3 1]
 [4 2 0]
 [4 0 4]
 [0 0 3]
 [1 3 4]]
[[2 4 2]
 [4 3 3]
 [0 1 4]
 [4 4 0]
 [3 0 2]
 [2 3 1]
 [4 2 0]
 [4 0 4]
 [0 0 3]
 [1 3 4]]


In [33]:
# 95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [34]:
# 96. Given a two dimensional array, how to extract unique rows?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


In [35]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.24469133, 0.28091286, 0.29266274, 0.10898853, 0.03205606,
        0.07818212, 0.29031069, 0.20572539, 0.34100902, 0.13191312],
       [0.24356824, 0.27962353, 0.29131948, 0.10848829, 0.03190893,
        0.07782328, 0.28897822, 0.20478115, 0.33944386, 0.13130766],
       [0.01668733, 0.01915755, 0.01995886, 0.00743274, 0.00218614,
        0.00533182, 0.01979845, 0.01402995, 0.02325595, 0.00899614],
       [0.08367661, 0.09606321, 0.1000813 , 0.03727059, 0.01096215,
        0.02673578, 0.09927697, 0.0703515 , 0.11661418, 0.04511007],
       [0.5109625 , 0.58660002, 0.61113602, 0.22758898, 0.06693921,
        0.16325928, 0.60622449, 0.42959413, 0.71209234, 0.27545993],
       [0.42787019, 0.49120761, 0.51175358, 0.19057865, 0.05605361,
        0.13671019, 0.50764076, 0.35973389, 0.59629247, 0.23066487],
       [0.09519057, 0.10928158, 0.11385255, 0.04239905, 0.01247055,
        0.03041465, 0.11293755, 0.08003192, 0.13266037, 0.05131725],
       [0.38282588, 0.4394954 , 0.4578783

In [36]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [37]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [38]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.31204074  0.0089699 ]
